trigger:  
 - main    # when someone pushes to main branch this pipeline will be triggered automatically.

pool:  
    vmImage: 'ubuntu-latest'    # azure devops creates a temporary virtual machine with ubntu_latest image to run the pipeline.
                                #Everything happens on this temporary build agent.

variables:                                        #we use variables so they can be reused throughout the pipeline.
        imageRepository: backend
        dockerfilePath: backend/Dockerfile
        tag: $(Build.BuildId)


