trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: backend
  dockerfilePath: backend/Dockerfile
  containerRegistry: threetierpp
  serviceConnection: threetierapp
  tag: $(Build.BuildId)

steps:

- checkout: self

- script: |
    pwd
    ls -R
  displayName: 'Verify Repository'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'

- script: |
    cd backend
    npm install
  displayName: 'Install Backend Dependencies'

- task: Docker@2
  displayName: 'Build Backend Image'
  inputs:
    command: build
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    tags: |
      $(tag)

- task: Docker@2
  displayName: 'Push Backend Image to ACR'
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(serviceConnection)
    tags: |
      $(tag)